ARG BASE_IMAGE="ghcr.io/gbraad-homelab/private-base"
ARG BASE_VERSION="latest"

FROM ${BASE_IMAGE}:${BASE_VERSION}

COPY assets/jellyfin-folders.service /etc/systemd/system

RUN dnf install --nogpgcheck -y \
        https://dl.fedoraproject.org/pub/epel/epel-release-latest-$(rpm -E %rhel).noarch.rpm \
        https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-$(rpm -E %rhel).noarch.rpm \
        https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-$(rpm -E %rhel).noarch.rpm \
    && dnf install -y \
        jellyfin \
    && dnf install -y \
        davfs2 \
    && dnf clean all \
    && rm -rf /var/cache/yum \
    && systemctl enable jellyfin \
    && systemctl enable jellyfin-folders.service

ENTRYPOINT ["/sbin/init"]
