ARG BASE_IMAGE="ghcr.io/gbraad-homelab/private-base"
ARG BASE_VERSION="latest"

FROM ${BASE_IMAGE}:${BASE_VERSION}

RUN dnf install -y \
    https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
    https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm \
    && dnf config-manager setopt fedora-cisco-openh264.enabled=1 \
    && dnf install -y jellyfin \
    && dnf install -y davfs2 \
    && dnf clean all \
    && rm -rf /var/cache/yum \
    && mkdir /var/lib/jellyfin \
    && chown jellyfin:jellyfin /var/lib/jellyfin \
    && mkdir /var/log/jellyfin \
    && chown jellyfin:jellyfin /var/log/jellyfin \
    && mkdir /var/cache/jellyfin \
    && chown jellyfin:jellyfin /var/cache/jellyfin

# systemd
RUN systemctl enable jellyfin
ENTRYPOINT ["/sbin/init"]
